const BASE =
  process.env.NEXT_PUBLIC_SERVER_BASE_URL?.replace(/\/$/, "") ||
  "http://localhost:3001";

export type Role = "user" | "ai" | "system";
export interface Message {
  id?: string;
  createdAt?: string;
  role: Role;
  data?: unknown;
  threadId?: string;
}
export interface AIError {
  code: string;
  message: string;
  retryable?: boolean;
  details?: unknown;
}
export interface AIMeta {
  threadId: string;
  messageId?: string;
  createdAt: string;
  model?: string;
  latency_ms?: number;
}
export interface AIContinuation {
  type: "none" | "stream" | "paginate" | "followup_required";
  cursor?: string;
  hint?: string;
}

export interface ChatResponse {
  ok: boolean;
  reply?: string;
  suggestions?: string[];
  modules: unknown[];
  error?: AIError;
  meta: AIMeta;
  continuation?: AIContinuation;
}

async function http<T>(path: string, init?: RequestInit): Promise<T> {
  const res = await fetch(`${BASE}${path}`, {
    ...init,
    headers: {
      "Content-Type": "application/json",
      "ngrok-skip-browser-warning": "true",  // Skip ngrok warning page
      ...(init?.headers || {}),
    },
  });
  if (!res.ok) {
    let detail: unknown;
    try {
      detail = await res.json();
    } catch {}
    throw new Error(
      `HTTP ${res.status} ${res.statusText}` +
        (detail ? ` - ${JSON.stringify(detail)}` : "")
    );
  }
  return (await res.json()) as T;
}

// Create a new thread (generic, without user context)
export function createThread(): Promise<{
  threadId: string;
  createdAt: string;
}> {
  return http("/api/thread", { method: "POST" });
}

// Get or create the latest thread for a user, optionally filtered by activity
export function getOrCreateUserThread(
  userId: string,
  activityId?: string
): Promise<{
  threadId: string;
  createdAt: string;
  activityId?: string;
}> {
  return http("/api/thread", {
    method: "POST",
    body: JSON.stringify({ userId, activityId })
  });
}

// Get all messages for a specific thread
export function getThreadMessages(threadId: string): Promise<{
  threadId: string;
  messages: Message[];
}> {
  return http(`/api/thread/${threadId}/messages`, { method: "GET" });
}

// HTTP chat reply only
export function postChatReply(
  threadId: string | undefined,
  message: string,
  userId: string,
  signal?: AbortSignal
): Promise<{ ok: boolean; reply?: string; error?: any; meta: any }> {
  return http("/api/chat/reply", {
    method: "POST",
    body: JSON.stringify({ threadId, message, userId }),
    signal,
  });
}

// HTTP combined generate (reply + memory processing)
export function postGenerate(
  threadId: string | undefined,
  message: string,
  userId: string,
  source?: string,
  signal?: AbortSignal
): Promise<{ ok: boolean; reply?: string; operationResults?: any[]; profileAutoUpdate?: any; error?: any; meta: any }> {
  return http("/api/chat/generate", {
    method: "POST",
    body: JSON.stringify({ threadId, message, userId, source: source || "conversation" }),
    signal,
  });
}

// HTTP start interview session
// Returns the first (or existing pending) interviewer question.
export function postStartInterview(
  threadId: string,
  userId: string,
  activityId: string,
  signal?: AbortSignal
): Promise<{ ok: boolean; replyQuestion?: string; questionMessageId?: string; interviewEnded?: boolean; error?: any; meta: any }> {
  return http("/api/chat/start-interview", {
    method: "POST",
    body: JSON.stringify({ threadId, userId, activityId }),
    signal,
  });
}

// HTTP Interviewer mode message reply
// Returns the next interview question generated by AI.
export function postInterviewMessage(
  threadId: string,
  message: string,
  userId: string,
  activityId: string,
  signal?: AbortSignal
): Promise<{ ok: boolean; replyQuestion?: string; questionMessageId?: string; interviewEnded?: boolean; error?: any; meta: any }> {
  return http("/api/chat/interview", {
    method: "POST",
    body: JSON.stringify({ threadId, message, userId, activityId }),
    signal,
  });
}

// HTTP process memory operations
export function postProcessMemory(
  threadId: string,
  userId: string,
  replyText: string,
  userMessage: string,
  source?: string
): Promise<{ ok: boolean; operationResults?: any[]; profileAutoUpdate?: any; error?: any }> {
  return http("/api/chat/process-memory", {
    method: "POST",
    body: JSON.stringify({ threadId, userId, replyText, userMessage, source }),
  });
}

// Health check (handy for readiness)
export function healthz(): Promise<{ ok: boolean }> {
  return http("/healthz", { method: "GET" });
}

// ===== Profile API =====

import type { Memory, ProfileSection } from "@/components/profile/types";

/**
 * API Response wrapper for profile endpoints
 */
export interface ProfileApiResponse<T = any> {
  status: number;
  message: string;
  apiId: string;
  version: string;
  requestId: string;
  timestamp: string;
  lang: string;
  data?: T;
  error?: {
    code: string;
    details?: any;
  };
}

/**
 * Profile data structure returned from backend
 */
export interface ProfileData {
  userId: string;
  name: string;
  title: string;
  bio: string;
  sections: ProfileSection[];
  memories: Memory[];
}

/**
 * User model data (from User table only)
 */
export interface UserData {
  userId: string;
  name: string;
  title: string;
  bio: string;
}

/**
 * Profile view response structure (BFF endpoint)
 */
interface ProfileViewResponse {
  profileView: {
    userId: string;
    name: string;
    title: string;
    bio: string;
    sections: ProfileSection[];
    memories?: Memory[];
  };
}

/**
 * Get User model data only (from User table)
 * 
 * @param userId - The user ID to fetch
 * @returns Promise with user data
 */
export async function getUser(userId: string): Promise<UserData> {
  const response = await http<ProfileApiResponse<{ user: UserData }>>(
    `/api/users/${encodeURIComponent(userId)}`,
    { method: "GET" }
  );

  if (!response.data?.user) {
    throw new Error("No user data returned from API");
  }

  return response.data.user;
}

/**
 * Get complete profile view including user, sections, and optionally memories
 * This is a BFF (Backend-for-Frontend) endpoint
 * 
 * @param userId - The user ID to fetch profile for
 * @param includeMemories - Whether to include memories in the response
 * @returns Promise with complete profile data
 */
export async function getProfileView(userId: string, includeMemories: boolean = true): Promise<ProfileData> {
  const queryString = includeMemories ? '?include=memories' : '';
  const response = await http<ProfileApiResponse<ProfileViewResponse>>(
    `/api/profile-views/${encodeURIComponent(userId)}${queryString}`,
    { method: "GET" }
  );

  if (!response.data?.profileView) {
    throw new Error("No profile data returned from API");
  }

  const { profileView } = response.data;
  
  return {
    userId: profileView.userId,
    name: profileView.name,
    title: profileView.title,
    bio: profileView.bio,
    sections: profileView.sections,
    memories: profileView.memories || []
  };
}

/**
 * Get a specific profile section by section ID
 * 
 * @param userId - The user ID
 * @param sectionId - The section ID to fetch
 * @returns Promise with section data and related memories
 */
export async function getProfileSection(
  userId: string,
  sectionId: string
): Promise<{ section: ProfileSection; memories: Memory[] }> {
  const response = await http<ProfileApiResponse<{ section: ProfileSection; memories: Memory[] }>>(
    `/api/profile/${encodeURIComponent(userId)}/sections/${encodeURIComponent(sectionId)}`,
    { method: "GET" }
  );

  if (!response.data) {
    throw new Error("No section data returned from API");
  }

  return response.data;
}

/**
 * Profile generation result from backend
 */
export interface ProfileGenerationResult {
  userId: string;
  generatedAt: string;
  model: string;
  sectionsCount: number;
  latency_ms?: number;
}

/**
 * Generate user profile using AI and save to database
 * This triggers the complete flow:
 * 1. AI generates profile data
 * 2. Backend saves to database
 * 3. Returns the generated userId
 * 
 * @param userId - Optional: If provided, updates existing user profile; otherwise creates new user
 * @returns Promise with generation result including userId and metadata
 */
export async function generateProfile(userId?: string): Promise<ProfileGenerationResult> {
  console.log('[Frontend API] Generating profile...', userId ? `for userId: ${userId}` : 'for new user');
  
  const response = await http<ProfileApiResponse<ProfileGenerationResult>>(
    '/api/profile/generate',
    {
      method: 'POST',
      body: JSON.stringify({ userId: userId || undefined })
    }
  );

  if (!response.data) {
    throw new Error('No generation result returned from API');
  }

  return response.data;
}

// ===== Memory API =====

/**
 * Memory creation request body
 */
export interface CreateMemoryRequest {
  userId: string;
  type: 'user' | 'ai';
  content: string;
  source: string;
  categories: string[];  // Array of category tags
  sectionIds?: string[];
}

/**
 * Memory update request body
 */
export interface UpdateMemoryRequest {
  content?: string;
  source?: string;
  categories?: string[];  // Array of category tags
}

/**
 * Create a new memory
 * 
 * @param request - Memory creation data
 * @returns Promise with created memory
 */
export async function createMemory(request: CreateMemoryRequest): Promise<Memory> {
  console.log('[Frontend API] Creating memory...', request);
  
  const response = await http<ProfileApiResponse<{ memory: Memory }>>(
    '/api/memories',
    {
      method: 'POST',
      body: JSON.stringify(request)
    }
  );

  if (!response.data?.memory) {
    throw new Error('No memory data returned from API');
  }

  return response.data.memory;
}

/**
 * Update an existing memory
 * 
 * @param memoryId - The memory ID to update
 * @param request - Memory update data
 * @returns Promise with updated memory
 */
export async function updateMemory(
  memoryId: string,
  request: UpdateMemoryRequest
): Promise<Memory> {
  console.log('[Frontend API] Updating memory...', memoryId, request);
  
  const response = await http<ProfileApiResponse<{ memory: Memory }>>(
    `/api/memories/${encodeURIComponent(memoryId)}`,
    {
      method: 'PATCH',
      body: JSON.stringify(request)
    }
  );

  if (!response.data?.memory) {
    throw new Error('No memory data returned from API');
  }

  return response.data.memory;
}

/**
 * Delete a memory (supports soft and hard delete modes)
 * 
 * @param memoryId - The memory ID to delete
 * @param mode - Delete mode: 'soft' (add deleted tag) or 'hard' (actually delete from DB)
 * @returns Promise with deleted memory (soft mode) or empty object (hard mode)
 */
export async function deleteMemory(
  memoryId: string,
  mode: 'soft' | 'hard' = 'soft'
): Promise<Memory | null> {
  console.log('[Frontend API] Deleting memory...', memoryId, `mode: ${mode}`);
  
  const response = await http<ProfileApiResponse<{ memory?: Memory }>>(
    `/api/memories/${encodeURIComponent(memoryId)}?mode=${mode}`,
    {
      method: 'DELETE'
    }
  );

  // Hard delete returns empty data, soft delete returns updated memory
  return response.data?.memory || null;
}

/**
 * Profile auto-update result from backend
 */
export interface ProfileAutoUpdateResult {
  triggered: boolean;       // Whether profile update was actually triggered
  newCount?: number;        // New memory operation count
  message: string;          // Status message
  error?: string;           // Error if any
  profileData?: ProfileData; // Complete profile data if update was successful
}

/**
 * Trigger profile auto-update after memory operations
 * 
 * @param userId - User ID
 * @param successCount - Number of successful memory operations
 * @returns Promise with auto-update result including profileData if triggered
 */
export async function triggerProfileAutoUpdate(
  userId: string,
  successCount: number
): Promise<ProfileAutoUpdateResult> {
  console.log('[Frontend API] Triggering profile auto-update...', { userId, successCount });
  
  const response = await http<ProfileApiResponse<ProfileAutoUpdateResult>>(
    '/api/profile/trigger-auto-update',
    {
      method: 'POST',
      body: JSON.stringify({ userId, successCount })
    }
  );

  if (!response.data) {
    throw new Error('No auto-update result returned from API');
  }

  return response.data;
}

// ===== Auth API =====

/**
 * User data returned from auth endpoints
 */
export interface AuthUser {
  id: string;
  name: string | null;
  email: string | null;
  image?: string | null;
}

/**
 * Auth API response wrapper
 */
interface AuthResponse<T> {
  message: string;
  user?: T;
  error?: string;
}

/**
 * Sign up a new user
 * 
 * @param email - User email
 * @param password - User password (plain text, will be hashed on backend)
 * @param name - User name (optional)
 * @returns Promise with created user data
 */
export async function signUp(
  email: string,
  password: string,
  name?: string
): Promise<AuthUser> {
  const response = await http<AuthResponse<AuthUser>>(
    '/api/auth/signup',
    {
      method: 'POST',
      body: JSON.stringify({ email, password, name })
    }
  );

  if (!response.user) {
    throw new Error(response.error || 'Failed to create account');
  }

  return response.user;
}

/**
 * Verify user credentials (for NextAuth)
 * 
 * @param email - User email
 * @param password - User password
 * @returns Promise with user data if credentials are valid
 */
export async function verifyCredentials(
  email: string,
  password: string
): Promise<AuthUser> {
  const response = await http<AuthResponse<AuthUser>>(
    '/api/auth/verify-credentials',
    {
      method: 'POST',
      body: JSON.stringify({ email, password })
    }
  );

  if (!response.user) {
    throw new Error(response.error || 'Invalid credentials');
  }

  return response.user;
}

/**
 * Get g-eval score from AI server
 * 
 * @param userId - User ID for g-eval
 * @returns Promise with g-eval score
 */
export async function getGEval(userId: string): Promise<{ score: number }> {
  const response = await http<{ status: number; message: string; apiId: string; data: { score: number } }>(
    '/api/profile/g-eval',
    {
      method: 'POST',
      body: JSON.stringify({ userId })
    }
  );

  if (response.status !== 200 || !response.data) {
    throw new Error("Failed to fetch g-eval score");
  }

  return response.data;
}

/**
 * Get all activities with their questions
 * Used to populate the Activities page with activity cards
 * 
 * @returns Promise with all activities and their associated questions
 */
export async function getActivities(): Promise<{
  activities: Array<{
    id: string;
    name: string;
    description: string;
    category: string;
    createdAt: string;
    questions: Array<{
      id: string;
      questionText: string;
    }>;
  }>;
}> {
  const response = await http<any>(
    '/api/activities',
    {
      method: 'GET'
    }
  );

  if (!response.data?.activities) {
    throw new Error("Failed to fetch activities");
  }

  return response.data;
}

/**
 * Get activity status for a specific user
 * Includes information about completion status of each activity
 * 
 * @param userId - User ID
 * @returns Promise with activity statuses for the user
 */
export async function getActivityStatus(userId: string): Promise<{
  statuses: Array<{
    activityId: string;
    activityName: string;
    status: 'not_started' | 'in_progress' | 'completed';
    questionCount: number;
    answeredCount: number;
    extractedCount: number;
  }>;
}> {
  const response = await http<any>(
    `/api/activities/status/${userId}`,
    {
      method: 'GET'
    }
  );

  if (!response.data?.statuses) {
    throw new Error("Failed to fetch activity status");
  }

  return response.data;
}
