import { createOpenAPI } from 'fumadocs-openapi/server';
import * as path from 'node:path';

// Use pre-split files generated by generate-openapi.mjs
export const openapi = createOpenAPI({
  input: [path.join(process.cwd(), 'openapi/public-backend.json')],
});

export const aiOpenapi = createOpenAPI({
  input: [path.join(process.cwd(), 'openapi/ai-openapi.json')],
});
